import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
// import Demo from './demos/terminal/TerminalDemo'
import PostDemo from './demos/PostDemo'
import SliceDemo from './demos/SliceDemo'
import ReRender from './demos/ReRender'
import UseTransition from './demos/UseTransition'
import UseTransitionPage from './demos/UseTransitionPage'
import UseStatePart from './demos/UseStatePart'
import UseRefStyle from './demos/UseRefStyle'
import UseStateInitial from './demos/hooks/UseStateInitial'
import AntdSplitter from './demos/antd/AntdSplitter'
import SSEX from './demos/sse/AttatchmentDemo2'
import BubbleDemo from './demos/sse/BubbleDemo'

import RefObject from './interview/RefObject'
import SetCount from './interview/SetCount'
import ReactDemo from './interview/React-setState-timeout'

import QuillEditor from './playground/QuillEditor'

// import 'antd/dist/antd.css'
import './index.css'

import PageLeave from './demos/PageLeave'
import DocumentVisibility from './demos/DocumentVisibility'
import LocalStorage from './demos/LocalStorage2'
import ImageEditor from './demos/image-editor'
import RouterApp from './demos/router/App3'

import QueryDemo from './demos/query/todo'
import UploadDemo from './demos/antd/UploadDemo'
import TooltipDemo from './demos/antd/TooltipDemo'
import TransferDemo from './demos/antd/TransferDemo'
import CopyToClipboard from './demos/tools/CopyToClipboard'
import ScreenshotImage from './demos/tools/ScreenshotImage'
import MarkdownImage from './demos/markdown/Image'
import SingleInputTimePicker from './demos/antd/SingleInputTimePicker'
import TableEditDemo from './demos/antd/TableEditDemo'
import BlockDemo from './demos/router/App'

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(<TableEditDemo />)
